### ISSUE TITLE
Шаг: Знакомство с шаблоном приложения Advanced

### ISSUE THREAD

**Issue by wdesign22** [githubjeka/yii2-tutorial#15]
Настройку в main-local  сделал. 
Пытаюсь выполнить: php yii migrate
И получается:

Yii Migration Tool (based on Yii v2.0.3)

```
Exception 'yii\db\Exception' with message 'could not find driver'

in /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Connection.php:534

Stack trace:
#0 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Connection.php(836): yii\db\Connection->open()
#1 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Connection.php(823): yii\db\Connection->getMasterPdo()
#2 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Command.php(208): yii\db\Connection->getSlavePdo()
#3 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Command.php(816): yii\db\Command->prepare(true)
#4 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Command.php(350): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/mysql/Schema.php(198): yii\db\Command->queryAll()
#6 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/mysql/Schema.php(97): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/db/Schema.php(140): yii\db\mysql\Schema->loadTableSchema('migration')
#8 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/controllers/MigrateController.php(121): yii\db\Schema->getTableSchema('{{%migration}}', true)
#9 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(610): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#10 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(102): yii\console\controllers\BaseMigrateController->getNewMigrations()
#11 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#12 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#13 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#15 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#16 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('migrate', Array)
#17 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('migrate', Array)
#18 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /var/www/yii2-tutorial/yii2-tutorial/yii2-app-advanced/yii(31): yii\base\Application->run()
```

**Comment by githubjeka** [comment]
php-sqlite не стоит

Там же написано

> Обратите внимание, что для работы PHP и SQLite потребуется подключение php_pdo_sqlite. [Проверьте подключено ли оно у вас.](http://localhost:8888/yii2-tutorial/blob/step-0.1/scripts/helpers/check.php)

**Comment by wdesign22** [comment]
Спасибо. Я посмотрел что PDO стоит и успокоился.
